/* ═══════════════════════════════════════════════════════
   Code Builder — AdGenXAI Amber Atelier
   Prompt-to-code with live preview panel.
   OpenClaw agent integration: select any installed agent
   to drive code generation with its system prompt + model.
   ═══════════════════════════════════════════════════════ */

import { useState, useRef, useEffect, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Separator } from "@/components/ui/separator";
import { motion, AnimatePresence } from "framer-motion";
import {
  Code2, Play, Copy, Download, Sparkles, Eye, FileCode,
  Wand2, RotateCcw, ExternalLink, Bot, ChevronDown, X,
  Zap, CheckCircle2, MessageSquare, Layers, Settings2,
  ArrowRight, Cpu,
} from "lucide-react";
import { toast } from "sonner";
import { useAgent, ActiveAgent } from "@/contexts/AgentContext";
import { Link } from "wouter";

/* ─── Agent-aware code generation ───────────────────── */

const AGENT_CODE_OUTPUTS: Record<string, (prompt: string) => string> = {
  Development: (prompt) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${prompt.slice(0, 40)}</title>
  <script src="https://cdn.tailwindcss.com"><\/script>
</head>
<body class="bg-gray-950 text-white min-h-screen font-sans">
  <!-- Generated by Full-Stack Dev agent (OpenClaw) -->
  <!-- System: Expert React/Next.js developer. Production-ready TypeScript + Tailwind. -->
  <div class="max-w-5xl mx-auto px-6 py-16">
    <nav class="flex items-center justify-between mb-16 pb-6 border-b border-gray-800">
      <div class="flex items-center gap-3">
        <div class="w-8 h-8 bg-blue-500 rounded-lg flex items-center justify-center">
          <span class="text-white font-bold text-sm">&lt;/&gt;</span>
        </div>
        <span class="font-bold text-lg">DevApp</span>
      </div>
      <div class="flex items-center gap-6">
        <a href="#" class="text-gray-400 hover:text-white text-sm transition">Docs</a>
        <a href="#" class="text-gray-400 hover:text-white text-sm transition">API</a>
        <a href="#" class="text-gray-400 hover:text-white text-sm transition">GitHub</a>
        <button class="bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-lg text-sm font-medium transition">
          Get Started
        </button>
      </div>
    </nav>
    <div class="grid grid-cols-2 gap-12 items-center mb-20">
      <div>
        <div class="inline-flex items-center gap-2 bg-blue-500/10 text-blue-400 px-3 py-1 rounded-full text-xs mb-6">
          <span class="w-1.5 h-1.5 bg-blue-400 rounded-full animate-pulse"></span>
          v2.0 — Production Ready
        </div>
        <h1 class="text-4xl font-bold mb-4 leading-tight">${prompt || "Build something extraordinary"}</h1>
        <p class="text-gray-400 mb-8 leading-relaxed">TypeScript-first, fully typed, production-grade architecture. Built with best practices from day one.</p>
        <div class="flex gap-3">
          <button class="bg-blue-600 hover:bg-blue-500 text-white px-6 py-3 rounded-lg font-medium transition flex items-center gap-2">
            <span>npm install</span> <span class="font-mono text-blue-200">@devapp/core</span>
          </button>
          <button class="border border-gray-700 hover:border-gray-500 text-white px-6 py-3 rounded-lg font-medium transition">
            View Docs
          </button>
        </div>
      </div>
      <div class="bg-gray-900 border border-gray-800 rounded-xl p-6 font-mono text-sm">
        <div class="flex items-center gap-2 mb-4">
          <div class="w-3 h-3 rounded-full bg-red-500"></div>
          <div class="w-3 h-3 rounded-full bg-yellow-500"></div>
          <div class="w-3 h-3 rounded-full bg-green-500"></div>
          <span class="text-gray-500 text-xs ml-2">index.ts</span>
        </div>
        <pre class="text-gray-300 leading-relaxed"><span class="text-blue-400">import</span> { createApp } <span class="text-blue-400">from</span> <span class="text-green-400">'@devapp/core'</span>;

<span class="text-blue-400">const</span> app = createApp({
  <span class="text-yellow-400">name</span>: <span class="text-green-400">'my-app'</span>,
  <span class="text-yellow-400">version</span>: <span class="text-green-400">'1.0.0'</span>,
  <span class="text-yellow-400">strict</span>: <span class="text-purple-400">true</span>,
});

app.<span class="text-yellow-400">listen</span>(<span class="text-orange-400">3000</span>);</pre>
      </div>
    </div>
    <div class="grid grid-cols-3 gap-6">
      ${["Type Safe", "Zero Config", "Edge Ready"].map((f, i) => `<div class="bg-gray-900 border border-gray-800 rounded-xl p-6 hover:border-blue-500/40 transition">
        <div class="w-10 h-10 bg-blue-500/10 rounded-lg flex items-center justify-center mb-4">
          <span class="text-blue-400 text-lg">${["🔷", "⚡", "🌐"][i]}</span>
        </div>
        <h3 class="font-semibold mb-2">${f}</h3>
        <p class="text-gray-400 text-sm">Production-grade ${f.toLowerCase()} built into the core.</p>
      </div>`).join("")}
    </div>
  </div>
</body>
</html>`,

  Writing: (prompt) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${prompt.slice(0, 40) || "Blog"}</title>
  <script src="https://cdn.tailwindcss.com"><\/script>
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Inter:wght@400;500&display=swap" rel="stylesheet">
</head>
<body class="bg-stone-50 text-stone-900 min-h-screen" style="font-family:'Inter',sans-serif">
  <!-- Generated by Content Writer agent (OpenClaw) -->
  <!-- System: Professional copywriter. Conversion-focused. Brand voice consistency. -->
  <header class="border-b border-stone-200 py-6">
    <div class="max-w-3xl mx-auto px-6 flex items-center justify-between">
      <span class="font-bold text-xl" style="font-family:'Playfair Display',serif">The Studio</span>
      <nav class="flex gap-6 text-sm text-stone-500">
        <a href="#" class="hover:text-stone-900 transition">Articles</a>
        <a href="#" class="hover:text-stone-900 transition">About</a>
        <a href="#" class="hover:text-stone-900 transition">Newsletter</a>
      </nav>
    </div>
  </header>
  <main class="max-w-3xl mx-auto px-6 py-16">
    <article>
      <div class="flex items-center gap-3 mb-6">
        <span class="bg-purple-100 text-purple-700 px-3 py-1 rounded-full text-xs font-medium">Featured</span>
        <span class="text-stone-400 text-sm">March 22, 2026 · 8 min read</span>
      </div>
      <h1 class="text-4xl font-bold mb-6 leading-tight" style="font-family:'Playfair Display',serif">${prompt || "The Art of Compelling Copy"}</h1>
      <p class="text-stone-500 text-lg mb-8 leading-relaxed">Every word is a decision. The best copy doesn't feel like marketing — it feels like a conversation with someone who understands exactly what you need.</p>
      <div class="flex items-center gap-4 mb-10 pb-10 border-b border-stone-200">
        <div class="w-10 h-10 bg-purple-100 rounded-full flex items-center justify-center">
          <span class="text-purple-600 font-bold text-sm">CW</span>
        </div>
        <div>
          <p class="font-medium text-sm">Content Writer</p>
          <p class="text-stone-400 text-xs">OpenClaw Agent · Claude 3.5</p>
        </div>
      </div>
      <div class="prose prose-stone max-w-none space-y-6">
        <p class="leading-relaxed">The difference between copy that converts and copy that doesn't isn't about clever wordplay or flashy headlines. It's about understanding the reader's internal monologue — and meeting them exactly where they are.</p>
        <blockquote class="border-l-4 border-purple-400 pl-6 italic text-stone-600">
          "The best marketing doesn't feel like marketing." — Tom Fishburne
        </blockquote>
        <p class="leading-relaxed">When you lead with the pain point, you signal that you understand. When you follow with the solution, you earn trust. And when you close with a clear, low-friction CTA, you make the decision easy.</p>
        <h2 class="text-2xl font-bold mt-8" style="font-family:'Playfair Display',serif">The Three-Part Framework</h2>
        <ol class="space-y-3 text-stone-600">
          <li class="flex gap-3"><span class="font-bold text-purple-600">01.</span> Lead with the pain — acknowledge what's broken</li>
          <li class="flex gap-3"><span class="font-bold text-purple-600">02.</span> Pivot to the solution — show the better path</li>
          <li class="flex gap-3"><span class="font-bold text-purple-600">03.</span> Close with clarity — one action, no friction</li>
        </ol>
      </div>
    </article>
  </main>
</body>
</html>`,

  Analytics: (prompt) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${prompt.slice(0, 40) || "Analytics Dashboard"}</title>
  <script src="https://cdn.tailwindcss.com"><\/script>
</head>
<body class="bg-slate-950 text-white min-h-screen">
  <!-- Generated by Data Analyst agent (OpenClaw) -->
  <!-- System: Data analyst. Python, SQL, data visualization. Clear actionable insights. -->
  <div class="flex h-screen">
    <aside class="w-56 bg-slate-900 border-r border-slate-800 flex flex-col">
      <div class="p-4 border-b border-slate-800">
        <div class="flex items-center gap-2">
          <div class="w-7 h-7 bg-green-500 rounded-md flex items-center justify-center">
            <span class="text-white text-xs font-bold">DA</span>
          </div>
          <span class="font-semibold text-sm">DataView</span>
        </div>
      </div>
      <nav class="p-3 space-y-1 flex-1">
        ${["Overview", "Revenue", "Users", "Funnels", "Cohorts", "Reports"].map((item, i) => `<a href="#" class="flex items-center gap-2 px-3 py-2 rounded-lg text-sm ${i === 0 ? "bg-green-500/10 text-green-400" : "text-slate-400 hover:text-white hover:bg-slate-800"} transition">${item}</a>`).join("")}
      </nav>
    </aside>
    <main class="flex-1 overflow-auto p-6">
      <div class="flex items-center justify-between mb-6">
        <div>
          <h1 class="text-xl font-bold">${prompt || "Analytics Overview"}</h1>
          <p class="text-slate-400 text-sm mt-1">Last 30 days · Updated 2 min ago</p>
        </div>
        <button class="bg-green-600 hover:bg-green-500 text-white px-4 py-2 rounded-lg text-sm font-medium transition">Export Report</button>
      </div>
      <div class="grid grid-cols-4 gap-4 mb-6">
        ${[["Total Revenue","$84,291","↑ 12.4%","green"],["Active Users","12,847","↑ 8.1%","blue"],["Conversion","3.24%","↑ 0.8%","purple"],["Churn Rate","1.2%","↓ 0.3%","amber"]].map(([label, val, change, color]) => `<div class="bg-slate-900 border border-slate-800 rounded-xl p-4">
          <p class="text-slate-400 text-xs mb-2">${label}</p>
          <p class="text-2xl font-bold mb-1">${val}</p>
          <span class="text-${color}-400 text-xs font-medium">${change} vs last month</span>
        </div>`).join("")}
      </div>
      <div class="grid grid-cols-3 gap-4">
        <div class="col-span-2 bg-slate-900 border border-slate-800 rounded-xl p-5">
          <h3 class="font-semibold mb-4 text-sm">Revenue Trend</h3>
          <div class="flex items-end gap-2 h-32">
            ${[40,55,45,70,60,80,75,90,85,95,88,100].map((h, i) => `<div class="flex-1 bg-green-500/20 rounded-t hover:bg-green-500/40 transition cursor-pointer relative group" style="height:${h}%">
              <div class="absolute -top-6 left-1/2 -translate-x-1/2 bg-slate-700 text-xs px-1.5 py-0.5 rounded opacity-0 group-hover:opacity-100 transition whitespace-nowrap">$${(h * 843).toLocaleString()}</div>
            </div>`).join("")}
          </div>
          <div class="flex justify-between mt-2 text-xs text-slate-500">
            <span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span><span>Oct</span><span>Nov</span><span>Dec</span><span>Jan</span><span>Feb</span><span>Mar</span>
          </div>
        </div>
        <div class="bg-slate-900 border border-slate-800 rounded-xl p-5">
          <h3 class="font-semibold mb-4 text-sm">Top Segments</h3>
          <div class="space-y-3">
            ${[["Enterprise","42%","green"],["Pro","31%","blue"],["Starter","18%","purple"],["Free","9%","slate"]].map(([seg, pct, color]) => `<div>
              <div class="flex justify-between text-xs mb-1"><span>${seg}</span><span class="text-${color}-400">${pct}</span></div>
              <div class="h-1.5 bg-slate-800 rounded-full"><div class="h-full bg-${color}-500 rounded-full" style="width:${pct}"></div></div>
            </div>`).join("")}
          </div>
        </div>
      </div>
    </main>
  </div>
</body>
</html>`,

  Security: (prompt) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${prompt.slice(0, 40) || "Security Dashboard"}</title>
  <script src="https://cdn.tailwindcss.com"><\/script>
</head>
<body class="bg-gray-950 text-white min-h-screen font-mono">
  <!-- Generated by Security Auditor agent (OpenClaw) -->
  <!-- System: Cybersecurity expert. Code review, vulnerability assessment, best practices. -->
  <div class="max-w-4xl mx-auto px-6 py-12">
    <div class="flex items-center gap-3 mb-8">
      <div class="w-10 h-10 bg-red-500/10 border border-red-500/30 rounded-lg flex items-center justify-center">
        <span class="text-red-400 text-lg">🛡</span>
      </div>
      <div>
        <h1 class="font-bold text-lg">${prompt || "Security Audit Report"}</h1>
        <p class="text-gray-500 text-xs">Generated by Security Auditor · OpenClaw</p>
      </div>
      <div class="ml-auto flex items-center gap-2 bg-red-500/10 border border-red-500/30 px-3 py-1.5 rounded-lg">
        <span class="w-2 h-2 bg-red-500 rounded-full animate-pulse"></span>
        <span class="text-red-400 text-xs font-medium">3 Critical Issues</span>
      </div>
    </div>
    <div class="space-y-3 mb-8">
      ${[
        ["CRITICAL","SQL Injection","Unsanitized user input in /api/search endpoint","red"],
        ["CRITICAL","Hardcoded Secret","JWT_SECRET found in config.js line 42","red"],
        ["CRITICAL","No Rate Limiting","Brute force risk on /api/auth/login","red"],
        ["MEDIUM","CORS Misconfiguration","origin: '*' in production environment","yellow"],
        ["MEDIUM","Sensitive Data in localStorage","Auth tokens stored client-side","yellow"],
        ["LOW","Missing CSP Headers","No Content-Security-Policy configured","blue"],
      ].map(([sev, title, desc, color]) => `<div class="border border-${color}-500/20 bg-${color}-500/5 rounded-lg p-4 flex items-start gap-4">
        <span class="text-${color}-400 text-xs font-bold bg-${color}-500/10 px-2 py-0.5 rounded mt-0.5 shrink-0">${sev}</span>
        <div class="flex-1">
          <p class="font-semibold text-sm mb-1">${title}</p>
          <p class="text-gray-400 text-xs">${desc}</p>
        </div>
        <button class="text-xs text-${color}-400 hover:text-${color}-300 transition shrink-0">Fix →</button>
      </div>`).join("")}
    </div>
    <div class="bg-gray-900 border border-gray-800 rounded-xl p-5">
      <h3 class="font-bold text-sm mb-3 text-green-400">Recommended Fix — SQL Injection</h3>
      <pre class="text-xs text-gray-300 leading-relaxed"><span class="text-red-400">// ❌ Vulnerable</span>
const query = \`SELECT * FROM users WHERE name = '\${req.query.name}'\`;

<span class="text-green-400">// ✅ Safe — parameterized query</span>
const query = 'SELECT * FROM users WHERE name = $1';
const result = await db.query(query, [req.query.name]);</pre>
    </div>
  </div>
</body>
</html>`,

  Design: (prompt) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${prompt.slice(0, 40) || "Design System"}</title>
  <script src="https://cdn.tailwindcss.com"><\/script>
  <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=Space+Grotesk:wght@400;500;600&display=swap" rel="stylesheet">
</head>
<body class="bg-rose-50 text-stone-900 min-h-screen" style="font-family:'Space Grotesk',sans-serif">
  <!-- Generated by Brand Designer agent (OpenClaw) -->
  <!-- System: Brand designer. Visual identity systems. Cohesive, memorable brand experiences. -->
  <div class="max-w-4xl mx-auto px-8 py-16">
    <header class="flex items-center justify-between mb-20">
      <div class="flex items-center gap-3">
        <div class="w-10 h-10 bg-rose-400 rounded-2xl flex items-center justify-center">
          <span class="text-white font-bold">B</span>
        </div>
        <span class="font-semibold text-lg">Brand Studio</span>
      </div>
      <nav class="flex gap-6 text-sm text-stone-500">
        <a href="#" class="hover:text-stone-900 transition">Work</a>
        <a href="#" class="hover:text-stone-900 transition">Services</a>
        <a href="#" class="hover:text-stone-900 transition">Contact</a>
      </nav>
    </header>
    <div class="mb-20">
      <p class="text-rose-500 text-sm font-medium mb-4 tracking-widest uppercase">Design System</p>
      <h1 class="text-6xl font-bold leading-none mb-6" style="font-family:'DM Serif Display',serif">${prompt || "Beautiful by design"}</h1>
      <p class="text-stone-500 text-xl max-w-xl leading-relaxed">Every pixel is intentional. Every choice reinforces the brand. Design is not decoration — it's communication.</p>
    </div>
    <div class="grid grid-cols-2 gap-6 mb-12">
      <div class="bg-white rounded-3xl p-8 shadow-sm">
        <h3 class="font-semibold mb-4 text-sm text-stone-400 uppercase tracking-wider">Color Palette</h3>
        <div class="flex gap-3">
          ${["rose-400","stone-900","rose-100","stone-400","white"].map((c) => `<div class="w-12 h-12 rounded-xl bg-${c} border border-stone-100 shadow-sm"></div>`).join("")}
        </div>
      </div>
      <div class="bg-stone-900 rounded-3xl p-8">
        <h3 class="font-semibold mb-4 text-sm text-stone-400 uppercase tracking-wider">Typography</h3>
        <p class="text-white text-2xl font-bold mb-1" style="font-family:'DM Serif Display',serif">DM Serif Display</p>
        <p class="text-stone-400 text-sm">Space Grotesk for body text</p>
      </div>
    </div>
  </div>
</body>
</html>`,

  Marketing: (prompt) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${prompt.slice(0, 40) || "Marketing Landing"}</title>
  <script src="https://cdn.tailwindcss.com"><\/script>
</head>
<body class="bg-orange-950 text-white min-h-screen">
  <!-- Generated by SEO Optimizer agent (OpenClaw) -->
  <!-- System: SEO specialist. Keyword opportunities. Data-driven optimization. -->
  <div class="max-w-5xl mx-auto px-6 py-20">
    <div class="text-center mb-20">
      <div class="inline-flex items-center gap-2 bg-orange-500/20 text-orange-300 px-4 py-2 rounded-full text-sm mb-8">
        <span class="w-2 h-2 bg-orange-400 rounded-full"></span>
        SEO-Optimized · Conversion-Ready
      </div>
      <h1 class="text-5xl font-bold mb-6 leading-tight">${prompt || "Rank #1. Convert More."}</h1>
      <p class="text-orange-200/70 text-xl max-w-2xl mx-auto mb-10">Built with semantic HTML, structured data, and conversion-focused copy. Every element serves a purpose.</p>
      <div class="flex gap-4 justify-center">
        <button class="bg-orange-500 hover:bg-orange-400 text-white px-8 py-4 rounded-xl font-semibold text-lg transition">Start Free Trial</button>
        <button class="border border-orange-500/30 text-orange-200 px-8 py-4 rounded-xl font-semibold text-lg hover:border-orange-400 transition">See Results</button>
      </div>
    </div>
    <div class="grid grid-cols-3 gap-6">
      ${[["12.4x","Average ROI","Clients see 12x return within 90 days"],["#1","Search Rankings","Top position for target keywords"],["340%","Traffic Growth","Organic growth in first quarter"]].map(([num, label, desc]) => `<div class="bg-orange-900/30 border border-orange-500/20 rounded-2xl p-6 text-center">
        <p class="text-4xl font-bold text-orange-400 mb-2">${num}</p>
        <p class="font-semibold mb-2">${label}</p>
        <p class="text-orange-200/60 text-sm">${desc}</p>
      </div>`).join("")}
    </div>
  </div>
</body>
</html>`,
};

function getDefaultCode(prompt: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${prompt.slice(0, 40) || "My App"}</title>
  <script src="https://cdn.tailwindcss.com"><\/script>
</head>
<body class="bg-gray-950 text-white min-h-screen">
  <div class="max-w-4xl mx-auto px-6 py-20">
    <nav class="flex items-center justify-between mb-20">
      <h1 class="text-2xl font-bold text-amber-400">AdGenXAI</h1>
      <div class="flex gap-4">
        <a href="#" class="text-gray-400 hover:text-white transition">Features</a>
        <a href="#" class="text-gray-400 hover:text-white transition">Pricing</a>
        <button class="bg-amber-500 text-black px-4 py-2 rounded-lg font-medium hover:bg-amber-400 transition">Get Started</button>
      </div>
    </nav>
    <div class="text-center">
      <span class="inline-block bg-amber-500/10 text-amber-400 px-4 py-1.5 rounded-full text-sm mb-6">✨ Built with AdGenXAI</span>
      <h2 class="text-5xl font-bold mb-6 leading-tight">${prompt || "Build something extraordinary"}</h2>
      <p class="text-gray-400 text-lg max-w-xl mx-auto mb-8">This page was generated in seconds using AI. Edit the prompt to customize it further.</p>
      <div class="flex gap-4 justify-center">
        <button class="bg-amber-500 text-black px-8 py-3 rounded-lg font-semibold hover:bg-amber-400 transition">Start Free</button>
        <button class="border border-gray-700 text-white px-8 py-3 rounded-lg font-semibold hover:border-gray-500 transition">View Demo</button>
      </div>
    </div>
    <div class="grid grid-cols-3 gap-6 mt-20">
      <div class="bg-gray-900 border border-gray-800 rounded-xl p-6"><div class="w-10 h-10 bg-amber-500/10 rounded-lg flex items-center justify-center mb-4"><span class="text-amber-400 text-xl">⚡</span></div><h3 class="font-semibold mb-2">Lightning Fast</h3><p class="text-gray-400 text-sm">Optimized for speed with edge computing.</p></div>
      <div class="bg-gray-900 border border-gray-800 rounded-xl p-6"><div class="w-10 h-10 bg-amber-500/10 rounded-lg flex items-center justify-center mb-4"><span class="text-amber-400 text-xl">🔒</span></div><h3 class="font-semibold mb-2">Secure</h3><p class="text-gray-400 text-sm">Enterprise-grade security built in.</p></div>
      <div class="bg-gray-900 border border-gray-800 rounded-xl p-6"><div class="w-10 h-10 bg-amber-500/10 rounded-lg flex items-center justify-center mb-4"><span class="text-amber-400 text-xl">🎨</span></div><h3 class="font-semibold mb-2">Beautiful</h3><p class="text-gray-400 text-sm">Stunning design out of the box.</p></div>
    </div>
  </div>
</body>
</html>`;
}

const SAMPLE_CODE = getDefaultCode("");

const TEMPLATES = [
  { name: "Landing Page", prompt: "Build a modern dark-mode SaaS landing page with hero, features, and pricing" },
  { name: "Dashboard", prompt: "Create an analytics dashboard with charts, stats cards, and sidebar navigation" },
  { name: "Portfolio", prompt: "Design a minimal portfolio site with project grid and about section" },
  { name: "Blog", prompt: "Generate a blog layout with article cards, categories, and search" },
  { name: "API Docs", prompt: "Build a developer documentation page with code examples and endpoint reference" },
];

/* ─── Agent Picker Dialog ────────────────────────────── */
function AgentPickerDialog({
  open,
  onClose,
  installedAgents,
  activeAgent,
  onSelect,
}: {
  open: boolean;
  onClose: () => void;
  installedAgents: ActiveAgent[];
  activeAgent: ActiveAgent | null;
  onSelect: (agent: ActiveAgent | null) => void;
}) {
  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="font-heading flex items-center gap-2">
            <Bot className="h-5 w-5 text-primary" /> Select OpenClaw Agent
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-2 mt-2">
          {/* No agent option */}
          <button
            onClick={() => { onSelect(null); onClose(); }}
            className={`w-full flex items-center gap-3 p-3 rounded-xl border transition text-left ${
              !activeAgent ? "border-primary/40 bg-primary/5" : "border-border/40 hover:border-primary/20 hover:bg-muted/20"
            }`}
          >
            <div className="w-9 h-9 rounded-lg bg-muted/40 flex items-center justify-center shrink-0">
              <Sparkles className="h-4 w-4 text-muted-foreground" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-heading font-medium">Default (No Agent)</p>
              <p className="text-xs text-muted-foreground">Standard code generation</p>
            </div>
            {!activeAgent && <CheckCircle2 className="h-4 w-4 text-primary shrink-0" />}
          </button>

          {installedAgents.length === 0 ? (
            <div className="text-center py-8">
              <Bot className="h-10 w-10 text-muted-foreground/40 mx-auto mb-3" />
              <p className="text-sm text-muted-foreground mb-3">No agents installed yet</p>
              <Link href="/agents" onClick={onClose}>
                <Button size="sm" variant="outline" className="font-heading gap-1.5 bg-transparent text-xs">
                  <ArrowRight className="h-3.5 w-3.5" /> Browse OpenClaw Marketplace
                </Button>
              </Link>
            </div>
          ) : (
            <ScrollArea className="max-h-[320px]">
              <div className="space-y-2 pr-1">
                {installedAgents.map((agent) => {
                  const isActive = activeAgent?.id === agent.id;
                  return (
                    <button
                      key={agent.id}
                      onClick={() => { onSelect(agent); onClose(); }}
                      className={`w-full flex items-center gap-3 p-3 rounded-xl border transition text-left ${
                        isActive ? "border-primary/40 bg-primary/5" : "border-border/40 hover:border-primary/20 hover:bg-muted/20"
                      }`}
                    >
                      <div className={`w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center shrink-0`}>
                        <Bot className={`h-4 w-4 ${agent.iconColor}`} />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <p className="text-sm font-heading font-medium truncate">{agent.name}</p>
                          <Badge variant="secondary" className="text-[10px] px-1.5 py-0 shrink-0">{agent.category}</Badge>
                        </div>
                        <p className="text-xs text-muted-foreground truncate">{agent.model}</p>
                      </div>
                      {isActive && <CheckCircle2 className="h-4 w-4 text-primary shrink-0" />}
                    </button>
                  );
                })}
              </div>
            </ScrollArea>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

/* ─── Main Page ──────────────────────────────────────── */
export default function CodePage() {
  const { activeAgent, setActiveAgent, installedAgents } = useAgent();
  const [prompt, setPrompt] = useState("");
  const [code, setCode] = useState(SAMPLE_CODE);
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState("preview");
  const [showAgentPicker, setShowAgentPicker] = useState(false);
  const [generationLog, setGenerationLog] = useState<string[]>([]);
  const [showLog, setShowLog] = useState(false);

  const handleGenerate = useCallback(() => {
    if (!prompt.trim()) return;
    setIsGenerating(true);
    setShowLog(true);

    const agentName = activeAgent?.name || "Default";
    const agentCategory = activeAgent?.category || "Development";

    const logs: string[] = [];
    const addLog = (msg: string) => { logs.push(msg); setGenerationLog([...logs]); };

    addLog(`[OpenClaw] Initializing code generation...`);
    setTimeout(() => addLog(`[Agent] ${agentName} (${agentCategory}) — system prompt loaded`), 300);
    setTimeout(() => addLog(`[Model] ${activeAgent?.model || "GPT-4.1"} — context window ready`), 600);
    setTimeout(() => addLog(`[Prompt] "${prompt.slice(0, 60)}${prompt.length > 60 ? "..." : ""}"`), 900);
    setTimeout(() => addLog(`[Generate] Building HTML + Tailwind output...`), 1200);
    setTimeout(() => {
      addLog(`[Complete] Code generated successfully ✓`);
      const generator = AGENT_CODE_OUTPUTS[agentCategory] || getDefaultCode;
      setCode(generator(prompt));
      setIsGenerating(false);
      setActiveTab("preview");
      toast.success(`${agentName} generated your app!`);
    }, 2000);
  }, [prompt, activeAgent]);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    toast.success("Code copied to clipboard");
  };

  const handleDownload = () => {
    const blob = new Blob([code], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "app.html";
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Downloaded app.html");
  };

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between h-14 px-4 border-b border-border/40 shrink-0">
        <div className="flex items-center gap-3">
          <Code2 className="h-5 w-5 text-primary" />
          <h1 className="font-heading font-semibold">Code Builder</h1>
          <Badge variant="secondary" className="text-xs font-heading">
            <Eye className="h-3 w-3 mr-1" /> Live Preview
          </Badge>
        </div>
        <div className="flex items-center gap-2">
          {/* Agent selector button */}
          <button
            onClick={() => setShowAgentPicker(true)}
            className={`flex items-center gap-2 px-3 py-1.5 rounded-lg border text-xs font-heading transition-all ${
              activeAgent
                ? "border-primary/40 bg-primary/5 text-primary hover:bg-primary/10"
                : "border-border/40 bg-transparent text-muted-foreground hover:text-foreground hover:border-border"
            }`}
          >
            <Bot className="h-3.5 w-3.5" />
            {activeAgent ? (
              <span className="max-w-[120px] truncate">{activeAgent.name}</span>
            ) : (
              <span>No Agent</span>
            )}
            <ChevronDown className="h-3 w-3 opacity-60" />
          </button>
          <Separator orientation="vertical" className="h-5 opacity-30" />
          <Button variant="outline" size="sm" className="gap-1.5 bg-transparent font-heading text-xs" onClick={handleCopy}>
            <Copy className="h-3.5 w-3.5" /> Copy
          </Button>
          <Button variant="outline" size="sm" className="gap-1.5 bg-transparent font-heading text-xs" onClick={handleDownload}>
            <Download className="h-3.5 w-3.5" /> Download
          </Button>
        </div>
      </div>

      {/* Active agent banner */}
      <AnimatePresence>
        {activeAgent && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden"
          >
            <div className="flex items-center gap-3 px-4 py-2 bg-primary/5 border-b border-primary/15">
              <div className="w-6 h-6 rounded-md bg-primary/15 flex items-center justify-center shrink-0">
                <Bot className={`h-3.5 w-3.5 ${activeAgent.iconColor}`} />
              </div>
              <div className="flex-1 min-w-0 flex items-center gap-3">
                <span className="text-xs font-heading font-semibold text-primary">{activeAgent.name}</span>
                <span className="text-xs text-muted-foreground hidden sm:block">is driving code generation</span>
                <div className="flex items-center gap-2">
                  <Badge variant="secondary" className="text-[10px] px-1.5 py-0">{activeAgent.category}</Badge>
                  <Badge variant="secondary" className="text-[10px] px-1.5 py-0">
                    <Cpu className="h-2.5 w-2.5 mr-1" />{activeAgent.model}
                  </Badge>
                  {activeAgent.tools.length > 0 && (
                    <Badge variant="secondary" className="text-[10px] px-1.5 py-0">
                      <Zap className="h-2.5 w-2.5 mr-1" />{activeAgent.tools.length} tools
                    </Badge>
                  )}
                </div>
              </div>
              <button
                onClick={() => setActiveAgent(null)}
                className="text-muted-foreground hover:text-foreground transition shrink-0"
              >
                <X className="h-3.5 w-3.5" />
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Prompt bar */}
      <div className="px-4 py-3 border-b border-border/40 bg-card/30 shrink-0">
        <div className="flex gap-2 max-w-4xl">
          <Input
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
            placeholder={
              activeAgent
                ? `Ask ${activeAgent.name} to build something...`
                : "Describe the app or website you want to build..."
            }
            className="flex-1 h-10 bg-input/30 border-border/40 font-heading text-sm"
            disabled={isGenerating}
          />
          <Button onClick={handleGenerate} disabled={isGenerating || !prompt.trim()} className="gap-1.5 font-heading text-sm">
            {isGenerating ? (
              <><RotateCcw className="h-4 w-4 animate-spin" /> Generating...</>
            ) : (
              <><Wand2 className="h-4 w-4" /> {activeAgent ? `Ask ${activeAgent.name.split(" ")[0]}` : "Generate"}</>
            )}
          </Button>
        </div>
        <div className="flex items-center gap-2 mt-2 flex-wrap">
          {TEMPLATES.map((t) => (
            <Button
              key={t.name}
              variant="outline"
              size="sm"
              className="text-xs bg-transparent font-heading h-7"
              onClick={() => setPrompt(t.prompt)}
            >
              {t.name}
            </Button>
          ))}
        </div>
      </div>

      {/* Generation log */}
      <AnimatePresence>
        {showLog && generationLog.length > 0 && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="overflow-hidden border-b border-border/40 bg-[oklch(0.14_0.02_55)]"
          >
            <div className="flex items-center justify-between px-4 py-1.5">
              <span className="text-xs font-mono text-muted-foreground">Generation Log</span>
              {!isGenerating && (
                <button onClick={() => setShowLog(false)} className="text-muted-foreground hover:text-foreground">
                  <X className="h-3 w-3" />
                </button>
              )}
            </div>
            <div className="px-4 pb-2 space-y-0.5 max-h-24 overflow-y-auto">
              {generationLog.map((log, i) => (
                <motion.p
                  key={i}
                  initial={{ opacity: 0, x: -4 }}
                  animate={{ opacity: 1, x: 0 }}
                  className="text-xs font-mono text-green-400/80"
                >
                  {log}
                </motion.p>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main content — code + preview */}
      <div className="flex-1 flex overflow-hidden">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col">
          <div className="px-4 pt-2 shrink-0">
            <TabsList className="bg-muted/30">
              <TabsTrigger value="preview" className="gap-1.5 font-heading text-xs">
                <Eye className="h-3.5 w-3.5" /> Preview
              </TabsTrigger>
              <TabsTrigger value="code" className="gap-1.5 font-heading text-xs">
                <FileCode className="h-3.5 w-3.5" /> Code
              </TabsTrigger>
              {activeAgent && (
                <TabsTrigger value="agent" className="gap-1.5 font-heading text-xs">
                  <Bot className="h-3.5 w-3.5" /> Agent
                </TabsTrigger>
              )}
            </TabsList>
          </div>

          <TabsContent value="preview" className="flex-1 p-4 pt-2 overflow-hidden">
            <div className="h-full rounded-xl border border-border/40 overflow-hidden bg-white relative">
              {/* Browser chrome */}
              <div className="flex items-center gap-2 px-4 py-2 bg-gray-100 border-b border-gray-200">
                <div className="flex gap-1.5">
                  <div className="w-3 h-3 rounded-full bg-red-400" />
                  <div className="w-3 h-3 rounded-full bg-yellow-400" />
                  <div className="w-3 h-3 rounded-full bg-green-400" />
                </div>
                <div className="flex-1 mx-4">
                  <div className="bg-white rounded-md px-3 py-1 text-xs text-gray-500 border border-gray-200 flex items-center gap-1.5">
                    <ExternalLink className="h-3 w-3" />
                    {activeAgent ? `openclaw://${activeAgent.name.toLowerCase().replace(/\s+/g, "-")}` : "localhost:3000"}
                  </div>
                </div>
                {activeAgent && (
                  <div className="flex items-center gap-1.5 text-xs text-gray-500">
                    <Bot className="h-3 w-3" />
                    <span>{activeAgent.name}</span>
                  </div>
                )}
              </div>
              <iframe
                srcDoc={code}
                className="w-full h-[calc(100%-40px)]"
                sandbox="allow-scripts"
                title="Live Preview"
              />
            </div>
          </TabsContent>

          <TabsContent value="code" className="flex-1 p-4 pt-2 overflow-hidden">
            <ScrollArea className="h-full rounded-xl border border-border/40 bg-[oklch(0.14_0.02_55)]">
              <pre className="p-4 text-sm font-mono text-foreground/90 leading-relaxed">
                <code>{code}</code>
              </pre>
            </ScrollArea>
          </TabsContent>

          {activeAgent && (
            <TabsContent value="agent" className="flex-1 p-4 pt-2 overflow-hidden">
              <ScrollArea className="h-full">
                <div className="space-y-4 max-w-2xl">
                  {/* Agent identity */}
                  <div className="flex items-center gap-4 p-4 rounded-xl bg-card border border-border/40">
                    <div className="w-12 h-12 rounded-2xl bg-primary/10 flex items-center justify-center">
                      <Bot className={`h-6 w-6 ${activeAgent.iconColor}`} />
                    </div>
                    <div className="flex-1">
                      <h3 className="font-heading font-bold">{activeAgent.name}</h3>
                      <p className="text-sm text-muted-foreground">{activeAgent.description}</p>
                    </div>
                    <Badge variant="default" className="text-xs font-heading">Active</Badge>
                  </div>

                  {/* Stats */}
                  <div className="grid grid-cols-3 gap-3">
                    {[
                      { label: "Model", value: activeAgent.model, icon: Cpu },
                      { label: "Category", value: activeAgent.category, icon: Layers },
                      { label: "Temperature", value: activeAgent.temperature?.toFixed(1) ?? "0.5", icon: Settings2 },
                    ].map((stat) => (
                      <div key={stat.label} className="p-3 rounded-lg bg-muted/20 border border-border/30 text-center">
                        <stat.icon className="h-4 w-4 text-primary mx-auto mb-1" />
                        <p className="text-xs text-muted-foreground">{stat.label}</p>
                        <p className="text-sm font-heading font-semibold mt-0.5">{stat.value}</p>
                      </div>
                    ))}
                  </div>

                  {/* System prompt */}
                  <div className="space-y-2">
                    <p className="text-sm font-heading font-medium flex items-center gap-1.5">
                      <MessageSquare className="h-3.5 w-3.5 text-primary" /> System Prompt
                    </p>
                    <div className="p-3 rounded-lg bg-muted/20 border border-border/30">
                      <pre className="text-xs text-muted-foreground whitespace-pre-wrap font-mono leading-relaxed">
                        {activeAgent.systemPrompt || "No system prompt configured."}
                      </pre>
                    </div>
                  </div>

                  {/* Tools */}
                  {activeAgent.tools.length > 0 && (
                    <div className="space-y-2">
                      <p className="text-sm font-heading font-medium flex items-center gap-1.5">
                        <Zap className="h-3.5 w-3.5 text-primary" /> Enabled Tools
                      </p>
                      <div className="flex flex-wrap gap-2">
                        {activeAgent.tools.map((t) => (
                          <Badge key={t} variant="secondary" className="text-xs font-heading">{t.replace(/_/g, " ")}</Badge>
                        ))}
                      </div>
                    </div>
                  )}

                  <Button
                    variant="outline"
                    className="font-heading gap-2 bg-transparent w-full"
                    onClick={() => setActiveAgent(null)}
                  >
                    <X className="h-4 w-4" /> Detach Agent
                  </Button>
                </div>
              </ScrollArea>
            </TabsContent>
          )}
        </Tabs>
      </div>

      {/* Agent picker dialog */}
      <AgentPickerDialog
        open={showAgentPicker}
        onClose={() => setShowAgentPicker(false)}
        installedAgents={installedAgents}
        activeAgent={activeAgent}
        onSelect={setActiveAgent}
      />
    </div>
  );
}
